exports.command = (cmd, file) => {
  const name = file.slice(-1)[0].slice(0, -3);
  const fullCategory = file.slice(0, -1);
  if (!cmd.conf) cmd.conf = {};
  cmd.conf.enabled = "enabled" in cmd.conf ? cmd.conf.enabled : true;
  cmd.conf.runIn = cmd.conf.runIn || ["text", "dm", "group"];
  cmd.conf.aliases = cmd.conf.aliases || [];
  cmd.conf.permLevel = cmd.conf.permLevel || [];
  cmd.conf.botPerms = cmd.conf.botPerms || [];
  cmd.conf.requiredFuncs = cmd.conf.requiredFuncs || [];
  cmd.conf.requiredSettings = cmd.conf.requiredSettings || [];
  if (!cmd.help) cmd.help = {};
  cmd.help.name = cmd.help.name || name;
  cmd.help.description = cmd.help.description || "No Description provided.";
  cmd.help.extendedHelp = cmd.help.extendedHelp || "";
  cmd.help.usage = cmd.help.usage || "";
  cmd.help.usageDelim = cmd.help.usageDelim || "";
  cmd.help.fullCategory = fullCategory;
  cmd.help.category = fullCategory[0] || "General";
  cmd.help.subCategory = fullCategory[1] || "General";
  return cmd;
};
